image: msrd0/gradle-cross

build:
  stage: build
  before_script:
    - git submodule update --init
    - mkdir -p .gradle
  script:
    - GRADLE_USER_HOME=.gradle gradle assemble
  artifacts:
    paths:
      - build/
      - .gradle/

deploy:
  stage: deploy
  before_script:
    - git submodule update --init
  script:
    - GRADLE_USER_HOME=.gradle gradle publish
  only:
    - master
