image: msrd0/gradle

build:
  stage: build
  before_script:
    - sudo apk add --no-cache ca-certificates cmake g++ gcc git make
    - git submodule update --init
    - mkdir -p .gradle
  script:
    - GRADLE_USER_HOME=.gradle gradle assemble
  artifacts:
    paths:
      - build/
      - .gradle/

deploy:
  stage: deploy
  script:
    - GRADLE_USER_HOME=.gradle gradle artifactoryPublish
  only:
    - master
